### ISSUE TITLE
Compatibility with version 8

### ISSUE THREAD

**Issue by typoman76** [Remo/concrete5-attribute-plain-text#2]
Hi Remo. Tried this on version 8.3.2. 
I can not install this. The strange message is: 
"attribute_plain_text kann ich installiert werden. Bitte überprüfen Sie, ob das Paket für Systemversion 5.7 verfügbar ist."

**Comment by Remo** [comment]
will check tomorrow

**Comment by Remo** [comment]
Works fine for me. What's the package folder name? Your structure should look like this

![image](https://user-images.githubusercontent.com/129864/39744027-29ffea0c-52a3-11e8-92e3-68f65a0b623c.png)

**Comment by typoman76** [comment]
Thanks Remo! Looked in the controller how to name it. But used dashes and not underscores. Thanks for the hint!
